name: Starting Mirroring

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  DURL: https://download.meizu.com/Firmware/Flyme/16s_Pro/8.20.7.21/cn_daily/20200721104004/04895e9f/update.zip
  TZ: Asia/Kolkata
  MIR: bit
  EXT: zip
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master      

       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install aria2 curl wget rsync sshpass
       - name: Download time
         run: |
            aria2c $DURL
       - name: Download transfer
         run: |
            curl -sL https://git.io/file-transfer | sh
       - name: upload to sf
         run: |
            wget https://raw.githubusercontent.com/aman25502/scripts/master/mirrorsftp.sh
            sudo chmod +x mirrorsftp.sh
            bash mirrorsftp.sh
            curl -s -X POST https://api.telegram.org/bot1294950340:AAF3nyGc8fOZtZ7wkAneQOkiORWZ_1YW2q8/sendMessage -d text="mirror file is uploaded to sourceforge" -d chat_id=-1001349965943                   
       - name: its upload time
         run: |
            ./transfer $MIR *.$EXT
